version: '3.4'

services:
  compile:
    build:
      context: .
      dockerfile: ./Dockerfile.build
    security_opt:
      - seccomp:unconfined
    volumes:
      - $PWD/src:/app
    working_dir: /app
    ports:
      - "3000:3000/udp"
      - "40000:40000"
    entrypoint: sh -c "reflex -c /reflex.conf"
